"""empty message

Revision ID: 049a0675004c
Revises: 2d59847b464b
Create Date: 2026-08-31 15:25:47.457840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049a0675004c'
down_revision = '2d59847b464b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('transcript',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('transcript',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
