"""empty message

Revision ID: 76e221b2f257
Revises: 57b874681db7
Create Date: 2026-08-30 16:27:18.950701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e221b2f257'
down_revision = '57b874681db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governing_body', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governing_body', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
