"""empty message

Revision ID: cf3d34fda5db
Revises: 98407789e39c
Create Date: 2026-09-03 15:31:39.064909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3d34fda5db'
down_revision = '98407789e39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('analysis_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('analysis_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('entity_count')

    # ### end Alembic commands ###
